package client;

import javax.swing.JPanel;
import pokemon.Pokemon;
import java.util.ArrayList;
import utilities.PokeColors;

public class PokedexPanel extends javax.swing.JPanel {

    JPanel contentPanel;
    ArrayList<Pokemon> pokedex;
    ArrayList<String> tempTypes;
    Pokemon temp;
    public PokedexPanel(JPanel panel, ArrayList<Pokemon> dex) {
        initComponents();
        this.contentPanel = panel;
        
        this.pokedex = dex;
        for (Pokemon pokemon : pokedex) {
            pokedexList.add(pokemon.getName(), pokemon.getPokedex_number());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pokedexList = new java.awt.List();
        pokemonNameValue = new java.awt.Label();
        pokemonNameLabel = new java.awt.Label();
        type2 = new java.awt.Label();
        weight = new java.awt.Label();
        imageLabel = new javax.swing.JLabel();
        dexNumberLabel1 = new java.awt.Label();
        type1 = new java.awt.Label();
        dexNumberValue = new java.awt.Label();
        weightLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        height = new java.awt.Label();

        setPreferredSize(new java.awt.Dimension(715, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Pokedex");

        pokedexList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pokedexListMouseClicked(evt);
            }
        });

        pokemonNameValue.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        pokemonNameLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pokemonNameLabel.setText("Name:");

        type2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        type2.setText("Dex no.");

        weight.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        imageLabel.setText("jLabel2");

        dexNumberLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dexNumberLabel1.setText("Dex no.");

        type1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        type1.setText("Dex no.");

        dexNumberValue.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        weightLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        weightLabel.setText("Height");

        heightLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        heightLabel.setText("Height");

        height.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pokedexList, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(type2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dexNumberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pokemonNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(pokemonNameValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dexNumberValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(weightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(heightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pokedexList, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dexNumberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dexNumberValue, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pokemonNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pokemonNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(type2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(heightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(weightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pokedexListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pokedexListMouseClicked
        // TODO add your handling code here:
        temp = pokedex.get(Integer.valueOf(pokedexList.getSelectedIndex()));
        dexNumberValue.setText(String.valueOf(temp.getPokedex_number()));
        pokemonNameValue.setText(temp.getName());
        imageLabel.setIcon(temp.getFrontIcon());
        height.setText(Double.toString(temp.getHeight()) + "m");
        weight.setText(Double.toString(temp.getWeight()) + "kg");
        
        tempTypes = temp.getTypes();
        
        type1.setText(tempTypes.get(0));
        type1.setForeground(PokeColors.getTypeColor(type1.getText()));
        if(tempTypes.size() == 2) {
            type2.setText(tempTypes.get(1));
            type2.setForeground(PokeColors.getTypeColor(type2.getText()));
        } else {
            type2.setText("");
        }
    }//GEN-LAST:event_pokedexListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label dexNumberLabel1;
    private java.awt.Label dexNumberValue;
    private java.awt.Label height;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private java.awt.List pokedexList;
    private java.awt.Label pokemonNameLabel;
    private java.awt.Label pokemonNameValue;
    private java.awt.Label type1;
    private java.awt.Label type2;
    private java.awt.Label weight;
    private javax.swing.JLabel weightLabel;
    // End of variables declaration//GEN-END:variables
}
