package client;

import java.awt.CardLayout;
import javax.swing.JPanel;

public class SelectGameModePanel extends javax.swing.JPanel {

    JPanel contentPanel;
    JPanel sidePanel;
    CardLayout card;
    
    public SelectGameModePanel(JPanel panel, JPanel sidePanel) {
        initComponents();
        this.contentPanel = panel;
        this.sidePanel = sidePanel;
        card = (CardLayout) sidePanel.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitleLabel = new javax.swing.JLabel();
        singleBattleButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(715, 400));

        panelTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        panelTitleLabel.setText("Select Game Mode");

        singleBattleButton.setText("Single Battle");
        singleBattleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleBattleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(singleBattleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(singleBattleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 277, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void singleBattleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleBattleButtonActionPerformed
        // TODO add your handling code here:
        card.show(sidePanel, "altCard");
    }//GEN-LAST:event_singleBattleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel panelTitleLabel;
    private javax.swing.JButton singleBattleButton;
    // End of variables declaration//GEN-END:variables
}
