package client;

import javax.swing.JPanel;
import java.awt.CardLayout;

public class SideNavPanel extends javax.swing.JPanel {

    JPanel contentPanel;
    
    CardLayout card;
    
    public SideNavPanel(JPanel panel) {
        initComponents();
        this.contentPanel = panel;
        
        // Create a call back to control the contentCard from here
        card = (CardLayout) contentPanel.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidenavPanel = new javax.swing.JPanel();
        createTrainerButton = new javax.swing.JButton();
        editTrainerButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        extrasLabel = new javax.swing.JLabel();
        movedexButton = new javax.swing.JButton();
        pokedexButton = new javax.swing.JButton();
        hallOfFameButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(715, 400));

        sidenavPanel.setBackground(new java.awt.Color(0, 51, 153));

        createTrainerButton.setText("Create A Trainer");
        createTrainerButton.setMaximumSize(new java.awt.Dimension(135, 40));
        createTrainerButton.setMinimumSize(new java.awt.Dimension(135, 40));
        createTrainerButton.setPreferredSize(new java.awt.Dimension(135, 40));
        createTrainerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTrainerButtonActionPerformed(evt);
            }
        });

        editTrainerButton.setText("View/Edit Trainers");
        editTrainerButton.setMaximumSize(new java.awt.Dimension(135, 40));
        editTrainerButton.setMinimumSize(new java.awt.Dimension(135, 40));
        editTrainerButton.setPreferredSize(new java.awt.Dimension(135, 40));
        editTrainerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTrainerButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.setPreferredSize(new java.awt.Dimension(135, 40));
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        extrasLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        extrasLabel.setForeground(new java.awt.Color(255, 255, 255));
        extrasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extrasLabel.setText("Extras");

        movedexButton.setText("View Movedex");
        movedexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movedexButtonActionPerformed(evt);
            }
        });

        pokedexButton.setText("View Pokedex");
        pokedexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokedexButtonActionPerformed(evt);
            }
        });

        hallOfFameButton.setText("Hall Of Fame");
        hallOfFameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallOfFameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidenavPanelLayout = new javax.swing.GroupLayout(sidenavPanel);
        sidenavPanel.setLayout(sidenavPanelLayout);
        sidenavPanelLayout.setHorizontalGroup(
            sidenavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidenavPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidenavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidenavPanelLayout.createSequentialGroup()
                        .addGroup(sidenavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editTrainerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pokedexButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidenavPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(sidenavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createTrainerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extrasLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movedexButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hallOfFameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        sidenavPanelLayout.setVerticalGroup(
            sidenavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidenavPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createTrainerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(editTrainerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(extrasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pokedexButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(movedexButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hallOfFameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(sidenavPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidenavPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createTrainerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTrainerButtonActionPerformed
        // TODO add your handling code here:
        card.show(contentPanel, "createTrainerCard");
    }//GEN-LAST:event_createTrainerButtonActionPerformed

    private void editTrainerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTrainerButtonActionPerformed
        // TODO add your handling code here:
        card.show(contentPanel, "viewEditTrainerCard");
    }//GEN-LAST:event_editTrainerButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void movedexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movedexButtonActionPerformed
        // TODO add your handling code here:
        card.show(contentPanel, "movedexCard");
    }//GEN-LAST:event_movedexButtonActionPerformed

    private void pokedexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokedexButtonActionPerformed
        // TODO add your handling code here:
        card.show(contentPanel, "pokedexCard");
    }//GEN-LAST:event_pokedexButtonActionPerformed

    private void hallOfFameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallOfFameButtonActionPerformed
        // TODO add your handling code here:
        card.show(contentPanel, "HOFCard");
    }//GEN-LAST:event_hallOfFameButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createTrainerButton;
    private javax.swing.JButton editTrainerButton;
    private javax.swing.JLabel extrasLabel;
    private javax.swing.JButton hallOfFameButton;
    private javax.swing.JButton movedexButton;
    private javax.swing.JButton pokedexButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JPanel sidenavPanel;
    // End of variables declaration//GEN-END:variables
}
