/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package battle.gui.utils;

import pokemon.Pokemon;

/**
 *
 * @author auston
 */
public class pokemonDetails extends javax.swing.JPanel {

    /**
     * Creates new form pokemonDetails
     */
    public pokemonDetails() {
        initComponents();
    }

    public void setLabels(Pokemon pokemon) {
        nameHolder.setText(pokemon.getName());
        lvlHolder.setText(Integer.toString(pokemon.getLevel()));
        if(pokemon.isHoldingItem()) {
            itemHolder.setText(pokemon.getItem().getName());
        } else {
            itemHolder.setText("none");
        }
        pokemonIcon.setIcon(pokemon.getFrontIcon());
        atkHolder.setText(Integer.toString(pokemon.getCurrent_attack()));
        defHolder.setText(Integer.toString(pokemon.getCurrent_defense()));
        spAtkHolder.setText(Integer.toString(pokemon.getCurrent_special_attack()));
        spDefHolder.setText(Integer.toString(pokemon.getCurrent_special_defense()));
        speedHolder.setText(Integer.toString(pokemon.getCurrent_speed()));
        
        move1.setText(pokemon.getMoveset()[0].getName());
        move2.setText(pokemon.getMoveset()[1].getName());
        move3.setText(pokemon.getMoveset()[2].getName());
        move4.setText(pokemon.getMoveset()[3].getName());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameHolder = new javax.swing.JLabel();
        atkLabel = new javax.swing.JLabel();
        atkHolder = new javax.swing.JLabel();
        defHolder = new javax.swing.JLabel();
        defenseLabel = new javax.swing.JLabel();
        spAtkLabel = new javax.swing.JLabel();
        spAtkHolder = new javax.swing.JLabel();
        spDefLabel = new javax.swing.JLabel();
        spDefHolder = new javax.swing.JLabel();
        speedLabel = new javax.swing.JLabel();
        speedHolder = new javax.swing.JLabel();
        lvlLabel = new javax.swing.JLabel();
        lvlHolder = new javax.swing.JLabel();
        itemLabel = new javax.swing.JLabel();
        itemHolder = new javax.swing.JLabel();
        pokemonIcon = new javax.swing.JLabel();
        atkLabel1 = new javax.swing.JLabel();
        move3 = new javax.swing.JLabel();
        move1 = new javax.swing.JLabel();
        move2 = new javax.swing.JLabel();
        move4 = new javax.swing.JLabel();

        jLabel1.setText("Pokemon Details");

        nameLabel.setText("Name:");

        nameHolder.setText("PokemonName");

        atkLabel.setText("Attack");

        atkHolder.setText("ATK STAT");

        defHolder.setText("DEF STAT");

        defenseLabel.setText("Defense");

        spAtkLabel.setText("Sp. Atk");

        spAtkHolder.setText("SP ATK STAT");

        spDefLabel.setText("Sp. Def");

        spDefHolder.setText("SP DEF STAT");

        speedLabel.setText("Speed");

        speedHolder.setText("SPEED STAT");

        lvlLabel.setText("Lv.");

        lvlHolder.setText("Level");

        itemLabel.setText("Item");

        itemHolder.setText("Level");

        atkLabel1.setText("Move Details");

        move3.setText("move3");

        move1.setText("Move1");

        move2.setText("Move2");

        move4.setText("move4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(speedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                            .addComponent(speedHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nameHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(defenseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(atkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(atkHolder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(defHolder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(spAtkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spAtkHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(spDefLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spDefHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lvlLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lvlHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itemLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pokemonIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atkLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(move1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(move2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(move3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(move4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(atkLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(move1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(move2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(move3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(move4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameLabel)
                                    .addComponent(nameHolder))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lvlLabel)
                                    .addComponent(lvlHolder))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(itemLabel)
                                    .addComponent(itemHolder))
                                .addGap(0, 154, Short.MAX_VALUE))
                            .addComponent(pokemonIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atkLabel)
                            .addComponent(atkHolder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(defenseLabel)
                            .addComponent(defHolder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spAtkLabel)
                            .addComponent(spAtkHolder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spDefLabel)
                            .addComponent(spDefHolder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(speedLabel)
                            .addComponent(speedHolder))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atkHolder;
    private javax.swing.JLabel atkLabel;
    private javax.swing.JLabel atkLabel1;
    private javax.swing.JLabel defHolder;
    private javax.swing.JLabel defenseLabel;
    private javax.swing.JLabel itemHolder;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lvlHolder;
    private javax.swing.JLabel lvlLabel;
    private javax.swing.JLabel move1;
    private javax.swing.JLabel move2;
    private javax.swing.JLabel move3;
    private javax.swing.JLabel move4;
    private javax.swing.JLabel nameHolder;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel pokemonIcon;
    private javax.swing.JLabel spAtkHolder;
    private javax.swing.JLabel spAtkLabel;
    private javax.swing.JLabel spDefHolder;
    private javax.swing.JLabel spDefLabel;
    private javax.swing.JLabel speedHolder;
    private javax.swing.JLabel speedLabel;
    // End of variables declaration//GEN-END:variables
}
