package gameInterface.redo;
import pokemon.Pokemon;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Auston
 */
public class battlePanel extends javax.swing.JPanel {

    /**
     * Creates new form battlePanel
     * @param left_pokemon
     * @param right_pokemon
     */
    public battlePanel(Pokemon left_pokemon, Pokemon right_pokemon) {
        initComponents();
        
        // TODO: Set up labels on battle startup
        rightPokemonName.setText(right_pokemon.getName());
        rightCurrentHP.setText(Integer.toString(right_pokemon.getCurrent_hp()));
        
        leftPokemonName.setText(left_pokemon.getName());
        leftCurrentHP.setText(Integer.toString(left_pokemon.getCurrent_hp()));
        eventTextArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightPokemonPanel = new javax.swing.JPanel();
        rightPokemonName = new javax.swing.JLabel();
        rightPokemonHpBar = new javax.swing.JProgressBar();
        rightPokemonLevel = new javax.swing.JLabel();
        rightMaxHP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rightCurrentHP = new javax.swing.JLabel();
        leftPokemonPanel = new javax.swing.JPanel();
        leftPokemonName = new javax.swing.JLabel();
        leftPokemonLevel = new javax.swing.JLabel();
        leftPokemonHpBar = new javax.swing.JProgressBar();
        leftMaxHP = new javax.swing.JLabel();
        leftSlash = new javax.swing.JLabel();
        leftCurrentHP = new javax.swing.JLabel();
        battleControlPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        battleEventArea = new javax.swing.JScrollPane();
        eventTextArea = new javax.swing.JTextArea();
        runButton = new javax.swing.JButton();
        bagButton = new javax.swing.JButton();
        pokeButton = new javax.swing.JButton();
        fightButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(655, 535));
        setMinimumSize(new java.awt.Dimension(655, 535));
        setPreferredSize(new java.awt.Dimension(655, 535));

        rightPokemonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Right Trainer Name"));

        rightPokemonName.setText("Right Pokemon Name");
        rightPokemonName.setToolTipText("");

        rightPokemonHpBar.setBackground(new java.awt.Color(255, 255, 255));
        rightPokemonHpBar.setForeground(new java.awt.Color(51, 204, 0));
        rightPokemonHpBar.setValue(100);
        rightPokemonHpBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rightPokemonLevel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rightPokemonLevel.setText("Right Pokemon lvl");

        rightMaxHP.setText("RightMax");

        jLabel3.setText("/");

        rightCurrentHP.setText("RightCur");

        javax.swing.GroupLayout rightPokemonPanelLayout = new javax.swing.GroupLayout(rightPokemonPanel);
        rightPokemonPanel.setLayout(rightPokemonPanelLayout);
        rightPokemonPanelLayout.setHorizontalGroup(
            rightPokemonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPokemonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPokemonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPokemonPanelLayout.createSequentialGroup()
                        .addComponent(rightPokemonName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(rightPokemonLevel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPokemonPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(rightPokemonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rightPokemonHpBar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPokemonPanelLayout.createSequentialGroup()
                                .addComponent(rightCurrentHP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rightMaxHP)
                                .addGap(25, 25, 25)))))
                .addContainerGap())
        );
        rightPokemonPanelLayout.setVerticalGroup(
            rightPokemonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPokemonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPokemonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightPokemonName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightPokemonLevel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPokemonHpBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rightPokemonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightMaxHP)
                    .addComponent(jLabel3)
                    .addComponent(rightCurrentHP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        leftPokemonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Left Trainer Name", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        leftPokemonName.setText("Left Pokemon Name");

        leftPokemonLevel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        leftPokemonLevel.setText("Left Pokemon lvl");

        leftPokemonHpBar.setBackground(new java.awt.Color(255, 255, 255));
        leftPokemonHpBar.setForeground(new java.awt.Color(51, 204, 0));
        leftPokemonHpBar.setValue(100);
        leftPokemonHpBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        leftMaxHP.setText("LeftMax");

        leftSlash.setText("/");

        leftCurrentHP.setText("LeftCur");

        javax.swing.GroupLayout leftPokemonPanelLayout = new javax.swing.GroupLayout(leftPokemonPanel);
        leftPokemonPanel.setLayout(leftPokemonPanelLayout);
        leftPokemonPanelLayout.setHorizontalGroup(
            leftPokemonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPokemonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPokemonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPokemonPanelLayout.createSequentialGroup()
                        .addComponent(leftPokemonName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(leftPokemonLevel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPokemonPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(leftPokemonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leftPokemonHpBar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPokemonPanelLayout.createSequentialGroup()
                                .addComponent(leftCurrentHP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(leftSlash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(leftMaxHP)
                                .addGap(25, 25, 25)))))
                .addContainerGap())
        );
        leftPokemonPanelLayout.setVerticalGroup(
            leftPokemonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPokemonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(leftPokemonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftPokemonName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftPokemonLevel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leftPokemonHpBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftPokemonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftMaxHP)
                    .addComponent(leftSlash)
                    .addComponent(leftCurrentHP)))
        );

        battleControlPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        eventTextArea.setEditable(false);
        eventTextArea.setColumns(20);
        eventTextArea.setRows(2);
        eventTextArea.setWrapStyleWord(true);
        eventTextArea.setAutoscrolls(false);
        battleEventArea.setViewportView(eventTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(battleEventArea, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(battleEventArea)
                .addContainerGap())
        );

        runButton.setBackground(new java.awt.Color(0, 51, 255));
        runButton.setForeground(new java.awt.Color(255, 255, 255));
        runButton.setText("RUN");
        runButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bagButton.setBackground(new java.awt.Color(255, 153, 0));
        bagButton.setForeground(new java.awt.Color(255, 255, 255));
        bagButton.setText("BAG");
        bagButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagButtonActionPerformed(evt);
            }
        });

        pokeButton.setBackground(new java.awt.Color(0, 153, 0));
        pokeButton.setForeground(new java.awt.Color(255, 255, 255));
        pokeButton.setText("POKEMON");
        pokeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        fightButton.setBackground(new java.awt.Color(204, 0, 0));
        fightButton.setForeground(new java.awt.Color(255, 255, 255));
        fightButton.setText("FIGHT");
        fightButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout battleControlPanelLayout = new javax.swing.GroupLayout(battleControlPanel);
        battleControlPanel.setLayout(battleControlPanelLayout);
        battleControlPanelLayout.setHorizontalGroup(
            battleControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(battleControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(battleControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, battleControlPanelLayout.createSequentialGroup()
                        .addComponent(fightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bagButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, battleControlPanelLayout.createSequentialGroup()
                        .addComponent(pokeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        battleControlPanelLayout.setVerticalGroup(
            battleControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, battleControlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(battleControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(battleControlPanelLayout.createSequentialGroup()
                        .addGroup(battleControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fightButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(bagButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(battleControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pokeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(runButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rightPokemonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(battleControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(leftPokemonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rightPokemonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(leftPokemonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(battleControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fightButtonActionPerformed

    private void bagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bagButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagButton;
    private javax.swing.JPanel battleControlPanel;
    private javax.swing.JScrollPane battleEventArea;
    private javax.swing.JTextArea eventTextArea;
    private javax.swing.JButton fightButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel leftCurrentHP;
    private javax.swing.JLabel leftMaxHP;
    private javax.swing.JProgressBar leftPokemonHpBar;
    private javax.swing.JLabel leftPokemonLevel;
    private javax.swing.JLabel leftPokemonName;
    private javax.swing.JPanel leftPokemonPanel;
    private javax.swing.JLabel leftSlash;
    private javax.swing.JButton pokeButton;
    private javax.swing.JLabel rightCurrentHP;
    private javax.swing.JLabel rightMaxHP;
    private javax.swing.JProgressBar rightPokemonHpBar;
    private javax.swing.JLabel rightPokemonLevel;
    private javax.swing.JLabel rightPokemonName;
    private javax.swing.JPanel rightPokemonPanel;
    private javax.swing.JButton runButton;
    // End of variables declaration//GEN-END:variables
}
